[package]
name = "voidspace-elevated"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[[bin]]
name = "voidspace-elevated"
path = "src/main.rs"
test = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
voidspace-fileops = { path = "../voidspace-fileops" }
windows = { workspace = true, features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
embed-resource = "3.0.11"

[dev-dependencies]
tempfile.workspace = true
